#!/usr/bin/env bash
# generate-config.sh — Write .quality-gates/config.yaml from Claude-provided flags.
# Claude (reasoning layer) provides all flags; this script writes deterministically.
# Usage: generate-config.sh [flags]
# POSIX/bash 3.2 compatible (macOS default shell)

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$SKILL_DIR/checks/lib-gate-utils.sh"

# ── Defaults ──────────────────────────────────────────────────────────────────
STACKS=""
COVERAGE=80
FILE_MAX_LOC=200
SCOPE_EXCLUDE=""
GATES="secrets,sast,deps,coverage,file-size"
SONAR_HOST_URL=""
SONAR_PROJECT_KEY=""
DAST_TAGS="owasp,sqli,xss"
DAST_BLOCK_SEVERITY="high"
DAST_ALLOW_LOCAL="false"
FORCE=false
DRY_RUN=false
NON_INTERACTIVE=false

# ── Flag parsing ───────────────────────────────────────────────────────────────
while [ $# -gt 0 ]; do
  case "$1" in
    --non-interactive)             NON_INTERACTIVE=true; shift ;;
    --force)                       FORCE=true; shift ;;
    --dry-run)                     DRY_RUN=true; shift ;;
    --stacks=*)                    STACKS="${1#--stacks=}"; shift ;;
    --coverage=*)                  COVERAGE="${1#--coverage=}"; shift ;;
    --file-max-loc=*)              FILE_MAX_LOC="${1#--file-max-loc=}"; shift ;;
    --exclude=*)                   SCOPE_EXCLUDE="${1#--exclude=}"; shift ;;
    --gates=*)                     GATES="${1#--gates=}"; shift ;;
    --sonar-host-url=*)            SONAR_HOST_URL="${1#--sonar-host-url=}"; shift ;;
    --sonar-project-key=*)         SONAR_PROJECT_KEY="${1#--sonar-project-key=}"; shift ;;
    --dast-tags=*)                 DAST_TAGS="${1#--dast-tags=}"; shift ;;
    --dast-block-severity=*)       DAST_BLOCK_SEVERITY="${1#--dast-block-severity=}"; shift ;;
    --dast-allow-local)            DAST_ALLOW_LOCAL="true"; shift ;;
    --dast-allow-local=*)          DAST_ALLOW_LOCAL="${1#--dast-allow-local=}"; shift ;;
    *)                             shift ;;
  esac
done

# ── Sanitize numeric values (strip non-numeric chars) ─────────────────────────
COVERAGE="${COVERAGE//[^0-9]/}"
FILE_MAX_LOC="${FILE_MAX_LOC//[^0-9]/}"
[ -z "$COVERAGE" ]     && COVERAGE=80
[ -z "$FILE_MAX_LOC" ] && FILE_MAX_LOC=200

# ── Build YAML sections ────────────────────────────────────────────────────────

# scope.exclude — sensible defaults + user extras via --exclude flag
build_exclude_yaml() {
  local yaml=""
  if [ -n "$SCOPE_EXCLUDE" ]; then
    local IFS_SAVE="$IFS"
    IFS=','
    for p in $SCOPE_EXCLUDE; do
      p="$(echo "$p" | tr -d ' ')"
      [ -n "$p" ] && yaml="${yaml}    - \"${p}\""$'\n'
    done
    IFS="$IFS_SAVE"
  fi
  yaml="${yaml}"'    - "**/node_modules/**"'$'\n'
  yaml="${yaml}"'    - "**/dist/**"'$'\n'
  yaml="${yaml}"'    - "**/__pycache__/**"'$'\n'
  yaml="${yaml}"'    - "**/*.test.*"'$'\n'
  yaml="${yaml}"'    - "**/migrations/**"'$'\n'
  echo "$yaml"
}

# Gate enabled/disabled block based on GATES flag
build_gates_yaml() {
  local enabled_gates="$GATES"
  local all_gates="secrets deps sast dast coverage file-size sonar"
  local yaml=""
  for gate in $all_gates; do
    # Check if gate name (or dash-normalized) appears in enabled list
    if echo "$enabled_gates" | grep -qE "(^|,)${gate}(,|$)"; then
      yaml="${yaml}  ${gate}:"$'\n'
      yaml="${yaml}    enabled: true"$'\n'
    else
      yaml="${yaml}  ${gate}:"$'\n'
      yaml="${yaml}    enabled: false"$'\n'
    fi
  done
  echo "$yaml"
}

# SonarQube section — only connection params (scan config goes in sonar-project.properties)
build_sonar_yaml() {
  local yaml=""
  [ -z "$SONAR_HOST_URL" ] && [ -z "$SONAR_PROJECT_KEY" ] && return 0

  yaml="sonar:"$'\n'
  [ -n "$SONAR_HOST_URL" ]    && yaml="${yaml}  host_url: ${SONAR_HOST_URL}"$'\n'
  [ -n "$SONAR_PROJECT_KEY" ] && yaml="${yaml}  project_key: ${SONAR_PROJECT_KEY}"$'\n'
  yaml="${yaml}  token: \"\"  # LEAVE EMPTY — use SONAR_TOKEN env var"$'\n'

  echo "$yaml"
}

# Build dast.tags as YAML list from comma-separated input
build_dast_tags_yaml() {
  local tags="$1"
  local yaml=""
  local IFS_SAVE="$IFS"
  IFS=','
  for tag in $tags; do
    tag="$(echo "$tag" | tr -d ' ')"
    [ -n "$tag" ] && yaml="${yaml}    - ${tag}"$'\n'
  done
  IFS="$IFS_SAVE"
  echo "$yaml"
}

# ── Assemble config YAML ───────────────────────────────────────────────────────
EXCLUDE_YAML="$(build_exclude_yaml)"
GATES_YAML="$(build_gates_yaml)"
SONAR_YAML="$(build_sonar_yaml)"
DAST_TAGS_YAML="$(build_dast_tags_yaml "$DAST_TAGS")"

GENERATED_YAML="# ADF Quality Gates — project config
# Generated by /quality-gates setup
# Stacks: ${STACKS:-unknown}

scope:
  exclude:
${EXCLUDE_YAML}
thresholds:
  coverage: ${COVERAGE}
  file_max_loc: ${FILE_MAX_LOC}

trivy:
  severity: CRITICAL,HIGH
  ignore_unfixed: true

semgrep:
  severity: ERROR
  changed_files_only: true

dast:
  tags:
${DAST_TAGS_YAML}
  block_severity: ${DAST_BLOCK_SEVERITY}
  allow_local: ${DAST_ALLOW_LOCAL}
  endpoints_file: .quality-gates/endpoints.txt

gates:
${GATES_YAML}
${SONAR_YAML}"

# ── Output ─────────────────────────────────────────────────────────────────────
QG_DIR=".quality-gates"
CONFIG_FILE="$QG_DIR/config.yaml"

if [ "$DRY_RUN" = "true" ]; then
  echo "# --- DRY RUN (not written) ---"
  echo "$GENERATED_YAML"
  exit 0
fi

if [ -f "$CONFIG_FILE" ] && [ "$FORCE" != "true" ]; then
  print_status "setup" "skip" "$CONFIG_FILE already exists (use --force to override)"
  exit 0
fi

mkdir -p "$QG_DIR"
printf '%s\n' "$GENERATED_YAML" > "$CONFIG_FILE"
print_status "setup" "ok" "created $CONFIG_FILE"
